name: test and deploy
on: 
  push: 
    branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build & Deploy
        uses: actions/setup-node@v3.6.0
      - run: npm install
      - run: npm test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.CREDENTIALS }}
      - name: ssh to server
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'todo-server'
          user: vfqq1066
          zone: 'australia-southeast1-b'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: |
            cd /home/vfqq1066/todo/todo-server
            git pull origin main
            npm install
            npm run build
            pm2 restart todo-server

