name: deploy
on: 
  push: 
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build & Deploy
        uses: actions/setup-node@v3.6.0
      - run: npm install
      - run: npm run build
      - name: ssh to server
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          command: |
            cd ~/remote_user/todo-server
            git pull origin master
            npm install
            pm2 restart todo-server

