name: deploy
on: 
  push: 
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build & Deploy
        uses: actions/setup-node@v3.6.0
      - run: npm install
      - run: npm run build
      - name: SCP to server
        uses: easingthemes/ssh-deploy@main
        with: 
          host: ${{ HOST }}
          username: ${{ USERNAME }}
          password: ${{ PASSWORD }}
          key: ${{SSH_KEY}}
          port: 22
          source: 'docs/'
          target: ''
